<a href="https://colab.research.google.com/github/TariboSamuel/ML-Zoomcamp/blob/main/ML_Zoomcamp_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**Question 1**

What's the version of Pandas that you installed

In [ ]:
pd.__version__

'1.5.3'

### Getting the data
For this homework, we'll use the California Housing Prices dataset

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-10-25 00:57:21--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.08s   

2023-10-25 00:57:21 (17.8 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [ ]:
df = pd.read_csv("housing.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

**Question 2**


How many columns are in the dataset?

* 10
* 6560
* 10989
* 20640

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

There are 10 columns

**Question 3**

Which columns in the dataset have missing values?

* `total_rooms`
* `total_bedrooms`
* both of the above
* no empty columns in the dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


`total_bedrooms` has null value

**Question 4**

How many unique values does the ocean_proximity column have?

* 3
* 5
* 7
* 9

In [ ]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

ans=5

**Question 5**

What's the average value of the median_house_value for the houses located near the bay?

* 49433
* 124805
* 259212
* 380440

In [ ]:
average_house_value_near_bay = df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()
print("Average median house value for houses near the bay:", average_house_value_near_bay)


Average median house value for houses near the bay: 259212.31179039303


**Question 6**

* Calculate the average of total_bedrooms column in the dataset.
* Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

Now, calculate the average of total_bedrooms again.

* Has it changed?
* Has it changed?

Hint: take into account only 3 digits after the decimal point.

* Yes
* No

In [ ]:
avg_total_bedrooms = df['total_bedrooms'].mean()
avg_total_bedrooms

537.8705525375618

In [ ]:
# Fill missing values in total_bedrooms with the mean value
df['total_bedrooms'].fillna(avg_total_bedrooms, inplace=True)

# Calculate the average of total_bedrooms again
new_avg_total_bedrooms = df['total_bedrooms'].mean()
new_avg_total_bedrooms

537.8705525375617

No, it didn't change

**Question 7**

* Select all the options located on islands.
* Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Compute the inverse of XTX.
* Create an array y with values [950, 1300, 800, 1000, 1300].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the last element of w?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

* -1.4812
* 0.001
* 5.6992
* 23.1233

In [ ]:
ocean_island = df[df['ocean_proximity'] == "ISLAND"][['housing_median_age', 'total_rooms', 'total_bedrooms']]
ocean_

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(ocean_island, *['housing_median_age'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(ocean_island, *['total_rooms'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(ocean_island, *['total_bedrooms'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(ocean_island, *['housing_median_age', 'total_rooms'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(ocean_island, *['total_rooms', 'total_bedrooms'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(ocean_island, *['housing_median_age'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(ocean_island, *['total_rooms'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(ocean_island, *['total_bedrooms'], **{})
chart

In [ ]:
#underlying numpy array
X = ocean_island.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [ ]:
#matrix-matrix multiplication to get transpose
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [ ]:
#imverse
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [ ]:
y = np.array([950, 1300, 800, 1000, 1300])

In [ ]:
# Calculate X^T
XT = X.T

# Multiply the inverse of XTX with X^T
result_temp = np.dot(XTX_inverse, XT)

# Multiply the above result with y
w = np.dot(result_temp, y)
w
print('the value of the last element of w is:', w[-1])

the value of the last element of w is: 5.699229455065586
